services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  database:
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      # Optionally, make the DB accessible from outside of the Docker network if needed
      - 3307:3306
    volumes:
      # Mount a volume for mariadb's persistent files for lifecylce outside of stack
      - "./database/data:/var/lib/mysql"
      # Mount the db_schema directory into the container to be auto-read and created in the new db
      - "./database/db_schema:/docker-entrypoint-initdb.d"

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/server.js:/app/server.js
      - ./frontend/dist:/app/dist
    environment:
      - PORT=80
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file: # this is new
      - .env # this is new

  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
    environment:
      - PORT=80
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file: # this is new
      - .env # this is new
